/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bancogerente;

import javax.swing.JOptionPane;

/**
 *
 * @author Guto
 */
public class Financiamento extends javax.swing.JInternalFrame {

    /**
     * Creates new form Financiamento
     */
    public Financiamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_aprovar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_emprestimos = new javax.swing.JTable();
        btn_fechar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Financiamento");

        btn_aprovar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_aprovar.setText("Aprovar");
        btn_aprovar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aprovarActionPerformed(evt);
            }
        });

        table_emprestimos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Antonio Souza", "1500", "21/07/2015", "(19)988556654", "36", "Casa", null},
                {"Felipe Rubens", "850000", "21/07/2015", "(19)33255688", "48", "Casa", null},
                {"Erick Berns", "1200", "21/07/2015", "(19)33255338", "48", "Carro", null},
                {"Dexter Morgan", "100000", "21/07/2015", "(19)99255688", "60", "Casa", null},
                {"Berry Allen", "5800", "21/07/2015", "(19)33255688", "60", "Carro", null},
                {"Will Smith", "6520", "21/07/2015", "(19)33255688", "72", "Carro", null},
                {"Oliver Queen", "90000", "21/07/2015", "(21)33255688", "48", "Casa", null},
                {"Bruce Wayne", "152000", "21/07/2015", "(19)33255688", "48", "Casa", null},
                {"Tony Stark", "200", "21/07/2015", "(19)33255688", "72", "Carro", null},
                {"Steve Rogers", "845", "21/07/2015", "(19)33255688", "84", "Carro", null},
                {"Hannah Montana", "785000", "22/07/2015", "(19)33255688", "84", "Casa", null},
                {"Ashley Morgan", "1200", "22/07/2015", "(19)33255688", "72", "Carro", null},
                {"Jennifer Anniston", "5880", "22/07/2015", "(19)33255688", "60", "Carro", null},
                {"Monica Corners", "15000", "22/07/2015", "(19)33255688", "60", "Carro", null},
                {"Henrique Cardoso", "25550", "22/07/2015", "(19)33255688", "60", "Carro", null}
            },
            new String [] {
                "Nome", "Valor (R$)", "Data de Vencimento", "Telefone", "Número de Parcelas", "Bem", "Aprovar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_emprestimos);

        btn_fechar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_fechar.setText("Fechar");
        btn_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_fechar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_aprovar)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_fechar)
                    .addComponent(btn_aprovar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aprovarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aprovarActionPerformed
        JOptionPane.showMessageDialog(null,"Financiamentos aprovados.");
        this.setVisible(false);
    }//GEN-LAST:event_btn_aprovarActionPerformed

    private void btn_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fecharActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btn_fecharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aprovar;
    private javax.swing.JButton btn_fechar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_emprestimos;
    // End of variables declaration//GEN-END:variables
}
