/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bancogerente;

import javax.swing.JOptionPane;

/**
 *
 * @author Guto
 */
public class GerarCartao extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cartao
     */
    public GerarCartao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ftf_conta = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JToggleButton();
        ftf_agencia = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_nome = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cb_tipoCartao = new javax.swing.JComboBox();
        btn_solicitar = new javax.swing.JToggleButton();
        btn_fechar = new javax.swing.JToggleButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_descricao = new javax.swing.JTextArea();
        rb_master = new javax.swing.JRadioButton();
        rb_cred = new javax.swing.JRadioButton();
        rb_visa = new javax.swing.JRadioButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Gerar Cartão");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        try {
            ftf_conta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Agencia:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Conta:");

        btn_buscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        try {
            ftf_agencia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Nome:");

        tf_nome.setEditable(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Tipo do cartão:");

        cb_tipoCartao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Student", "Silver", "Gold", "Platinum", "International", "Travel" }));
        cb_tipoCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tipoCartaoActionPerformed(evt);
            }
        });

        btn_solicitar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_solicitar.setText("Solicitar");
        btn_solicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_solicitarActionPerformed(evt);
            }
        });

        btn_fechar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_fechar.setText("Fechar");
        btn_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fecharActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Descrição:");

        ta_descricao.setEditable(false);
        ta_descricao.setColumns(20);
        ta_descricao.setRows(5);
        jScrollPane1.setViewportView(ta_descricao);

        rb_master.setText("MasterCard");

        rb_cred.setText("CrediCard");

        rb_visa.setText("Visa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_fechar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ftf_agencia, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ftf_conta, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                        .addComponent(btn_buscar))
                                    .addComponent(tf_nome)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(cb_tipoCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(rb_master)
                        .addGap(18, 18, 18)
                        .addComponent(rb_cred)
                        .addGap(18, 18, 18)
                        .addComponent(rb_visa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_solicitar)
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_buscar)
                    .addComponent(ftf_agencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftf_conta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cb_tipoCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_solicitar)
                    .addComponent(rb_visa)
                    .addComponent(rb_cred)
                    .addComponent(rb_master))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_fechar)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        if ((ftf_agencia.getText().toString().equals("1918")) && (ftf_conta.getText().toString().equals("19025-9"))) {
            tf_nome.setText("Guilherme Bernardes do Campo");
        } else {
            JOptionPane.showMessageDialog(null, "Cliente não encontrado.");
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_solicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_solicitarActionPerformed
       if (tf_nome.getText().equals("Guilherme Bernardes do Campo")){
            JOptionPane.showMessageDialog(null, "Cartão " + cb_tipoCartao.getSelectedItem().toString() + " solicitado." );
            this.setVisible(false);
       }else
           JOptionPane.showMessageDialog(null, "Por favor, selecione um cliente.");
    }//GEN-LAST:event_btn_solicitarActionPerformed

    private void btn_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fecharActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btn_fecharActionPerformed

    private void cb_tipoCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tipoCartaoActionPerformed
        switch (cb_tipoCartao.getSelectedItem().toString()) {
            case "Student":
                ta_descricao.setText("O cartão Student é exclusivo para estudantes e "
                        + "\n com uma série de descontos e estabelecimentos"
                        + "\n além da taxa de manutenção ser nula.");
            ;break;
            case "Silver":
                ta_descricao.setText("O cartão Silver é recomendado como primeiro "
                        + "\n cartão de créditos e conta com uma taxa de "
                        + "\n manutenção baixa.");
            ;break;
            case "Gold":
                ta_descricao.setText("O cartão Gold é recomendado para gastos "
                        + "\n de até 10 mil reais mensais e conta com"
                        + "\n atendimento personal 24/7.");
            ;break;
            case "Platinum":
                ta_descricao.setText("O cartão Platinum é destinado apenas para"
                        + "\n nossos melhores e mais refinados clientes,"
                        + "\n para gastos de até 50 mil reais mensais.");
            ;break;
            case "International":
                ta_descricao.setText("O cartão International é ótimo para"
                        + "\n fazer compras onlines e para aqueles que"
                        + "\n viajam muito ao exterior.");
            ;break;
            case "Travel":
                ta_descricao.setText("O cartão Travel é emitido para fins"
                        + "\n turísticos e são abastecidos conforme"
                        + "\n o critério do cliente.");
            ;

        }
    }//GEN-LAST:event_cb_tipoCartaoActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
       ta_descricao.setText("O cartão Student é exclusivo para estudantes e "
                        + "\n com uma série de descontos e estabelecimentos"
                        + "\n além da taxa de manutenção ser nula.");
    }//GEN-LAST:event_formComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_buscar;
    private javax.swing.JToggleButton btn_fechar;
    private javax.swing.JToggleButton btn_solicitar;
    private javax.swing.JComboBox cb_tipoCartao;
    private javax.swing.JFormattedTextField ftf_agencia;
    private javax.swing.JFormattedTextField ftf_conta;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb_cred;
    private javax.swing.JRadioButton rb_master;
    private javax.swing.JRadioButton rb_visa;
    private javax.swing.JTextArea ta_descricao;
    private javax.swing.JTextField tf_nome;
    // End of variables declaration//GEN-END:variables
}
