/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bancogerente;

/**
 *
 * @author Guto
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_abrirConta = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        btn_investimentos = new javax.swing.JToggleButton();
        btn_movimentacoes = new javax.swing.JToggleButton();
        btn_consultarInfoCliente = new javax.swing.JToggleButton();
        btn_emprestimos = new javax.swing.JToggleButton();
        btn_gerarCartao = new javax.swing.JToggleButton();
        btn_cancelarCartao = new javax.swing.JToggleButton();
        btn_transacoesGrandes = new javax.swing.JToggleButton();
        btn_estorno = new javax.swing.JToggleButton();
        btn_financiamento = new javax.swing.JToggleButton();
        btn_consorcio = new javax.swing.JToggleButton();
        btn_sair = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_abrirConta.setText("Abrir Conta");
        btn_abrirConta.setName("btn_abrirConta"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Operações");

        btn_investimentos.setText("Acompanhamento de Investimentos");
        btn_investimentos.setName("btn_investimentos"); // NOI18N

        btn_movimentacoes.setLabel("Movimentações Bancárias");
        btn_movimentacoes.setName("btn_movimentacoes"); // NOI18N

        btn_consultarInfoCliente.setText("Consultar Informações de Clientes");
        btn_consultarInfoCliente.setName("btn_consultaInfo"); // NOI18N

        btn_emprestimos.setText("Efetuar Empréstimos");
        btn_emprestimos.setName("btn_emprestimo"); // NOI18N

        btn_gerarCartao.setText("Gerar Cartão de Crédito");
        btn_gerarCartao.setName("btn_gerarCartao"); // NOI18N
        btn_gerarCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gerarCartaoActionPerformed(evt);
            }
        });

        btn_cancelarCartao.setText("Cancelar Cartão de Crédito");
        btn_cancelarCartao.setName("btn_cancelarCartao"); // NOI18N

        btn_transacoesGrandes.setText("Transações de Grandes Valores");
        btn_transacoesGrandes.setName("btn_transacoesGrande"); // NOI18N

        btn_estorno.setText("Realizar Estornos");
        btn_estorno.setName("btn_estornos"); // NOI18N

        btn_financiamento.setLabel("Financiamento");
        btn_financiamento.setName("btn_financiamento"); // NOI18N

        btn_consorcio.setLabel("Consórcio");
        btn_consorcio.setName("btn_consorcio"); // NOI18N

        btn_sair.setActionCommand("Sair");
        btn_sair.setLabel("Sair");
        btn_sair.setName("btn_sair"); // NOI18N
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_sair))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_investimentos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                                .addComponent(btn_transacoesGrandes))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_abrirConta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_cancelarCartao))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_movimentacoes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_estorno))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_consultarInfoCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_financiamento))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_gerarCartao)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_emprestimos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_consorcio)))))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_abrirConta)
                    .addComponent(btn_cancelarCartao))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_investimentos)
                    .addComponent(btn_transacoesGrandes))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_movimentacoes)
                    .addComponent(btn_estorno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_consultarInfoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_financiamento))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_emprestimos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_consorcio))
                .addGap(28, 28, 28)
                .addComponent(btn_gerarCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btn_sair)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_gerarCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gerarCartaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_gerarCartaoActionPerformed

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
       this.setVisible(false);
       TelaLogin login = new TelaLogin();
       login.show();
    }//GEN-LAST:event_btn_sairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_abrirConta;
    private javax.swing.JToggleButton btn_cancelarCartao;
    private javax.swing.JToggleButton btn_consorcio;
    private javax.swing.JToggleButton btn_consultarInfoCliente;
    private javax.swing.JToggleButton btn_emprestimos;
    private javax.swing.JToggleButton btn_estorno;
    private javax.swing.JToggleButton btn_financiamento;
    private javax.swing.JToggleButton btn_gerarCartao;
    private javax.swing.JToggleButton btn_investimentos;
    private javax.swing.JToggleButton btn_movimentacoes;
    private javax.swing.JToggleButton btn_sair;
    private javax.swing.JToggleButton btn_transacoesGrandes;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
